name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - uses: gitleaks/gitleaks-action@v3

      - uses: aquasecurity/trivy-action@v0.36.0

      # - uses: iosifache/semgrep-rules-manager

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Verify app builds
        run: python -c "import app"
      

