name: Security Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v3
        with:
          fetch-depth: 0
      
      - name: Trivy
        uses: lazy-actions/gitrivy@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: mininotes:latest
